blog/urls.py
from django.urls import path
from .views import create_blog_view, detail_blog_view

app_name="blog"

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view,name="detail")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.views import (
    regsitration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

from personal.views import (
    home_screen_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('account/', account_view, name='account'),
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls"), name="blog"),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),


    path('register/', regsitration_view, name='register'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver


def upload_location(instance, filename):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path


class BlogPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date_published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date_updated")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)  # -Creating a slug


pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blog/forms.py
from django import forms
from blog.models import BlogPost


class CreateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'image')

blog/views.py
from django.shortcuts import render,redirect, get_object_or_404
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm
from account.models import Account


def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form. is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
    context['form']= form
    return render(request, 'blog/create_blog.html', context)


def detail_blog_view(request, slug):
    context = {}
    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post
    return render(request, 'blog/detail_blog.html',context)

blog/templates/blog/create_blog.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>
		</div>
	</div>
</div>


{% endblock content %}

blog/templates/blog/detail_blog.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
    .card{
        max-width:700px;
    }
    .container{
    padding:20px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="card m-auto">
            <img class="card img-top" src="{{blog_post.image.url}}" alt="">
            <div class="card-body my-2 ">
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body|safe}}</p>
            </div>
            <div class="card-footer text-muted">
                <p>Last Updated:{{blog_post.date_updated}} </p>
                <p>Author: {{blog_post.author.username}}</p>
            </div>
        </div>
    </div>
</div>

{%endblock%}