blog/urls.py
from django.urls import path
from .views import create_blog_view, detail_blog_view

app_name="blog"

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view,name="detail")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.views import (
    regsitration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

from personal.views import (
    home_screen_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('account/', account_view, name='account'),
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls"), name="blog"),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),


    path('register/', regsitration_view, name='register'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.urls import path
from . import views


app_name = "personals"

urlpatterns = [
    path('', views.home_screen_view, name="home_screen_view")
]

personal/models.py
from django.db import models

PRIORITY = [
    ("L", "Low"),
    ("M", "Medium"),
    ("H", "High")
]


class Question(models.Model):
    title = models.CharField(max_length=255)
    question = models.TextField(max_length=400)
    priority = models.CharField(max_length=1, choices=PRIORITY)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Question List"
        verbose_name_plural = "Questions"

personal/views.py
from django.shortcuts import render
from account.models import Account


def home_screen_view(request):
    context = {}
    accounts = Account.objects.all()
    context['accounts'] = accounts
    return render(request, 'personal/home.html', context)

personal/templates/personal/home.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    @media (max-width:768px){
        .right-column{
            margin-left:0px;
        }
    }
    @media (min-width:){
        .right-column{
            margin-left:20px;
        }
    }
    .blog-post-container{
        background-color:#fff;
        margin-bottom:20px;
        width:100%;
    }
    .create-post-bar{
        background-color: #fff;
        margin-bottom: 20px;
    }
    .left-column{
        padding:0;
    }
    .right-column{
        padding:0;
    }


</style>

<div class="container">

    <div class=" row">
        <!--Right create post column if smaller than large-->
            <div class="create-post-bar d-lg-none col-lg-7 offset-lg-1 ">
                <a href="{% url 'blog:create' %}">Create Blog Post</a>
            </div>
        <!--Right create post smaller than large column-->
        <!--Blog Feed-->
            <div class="left-column col-lg-7 offset-lg-1">
                <div class="blog-post-container">
                    <p>Thingy</p>
                </div>
                <div class="blog-post-container">
                    <p>Thingy</p>
                </div>
                <div class="blog-post-container">
                    <p>Thingy</p>
                </div>
                <div class="blog-post-container">
                    <p>Thingy</p>
                </div>

            </div>
        <!--end of the Blog Feed-->.

        <!--Right create post column if larger than large-->
            <div class="right-column col-lg-3 d-lg-flex d-none flex-column ">
        <div class="create-post-bar">
            <p>STUFF</p>
            <p>STUFF</p>
            <p>STUFF</p>
            <p>STUFF</p>
            <p>STUFF</p>
            <a href="{% url 'blog:create' %}">Create Post</a>
        </div>
            </div>
        <!--Right create post column-->
    </div>

</div>
{%endblock content%}